---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
clickhouse_add_conf: "/etc/clickhouse-server/config.d/clickhouse.conf.yaml"